--- !distributed
# Configs passed in ignite.distributed.launcher.Parallel

backend: nccl  # 'nccl' for GPU or 'gloo' for CPU
nnodes: null  # number of machines to use
nproc_per_node: null  # number of GPUs per machine

# Used if nnodes > 1 (multi-machine training)):
node_rank: null
master_addr: null
master_port: null

init_method: null
