# Main paths
run_name: null  # (should be overwritten by the experiment config)
config_save_path: null # (should be overwritten by the experiment config)
dataset_path: null  # (should be overwritten by the experiment config)
output_dir: res # directory of results for an experiment will be `output_dir/run_name/``

# Globals
seed: 0
recover_model_step: 0  # the step to recover the model, 0 to not recover
save_attn: False
trunc_ampl: -1  # truncation amplitude of inputs (for test and validation only), negative to disable

# Additional default configs
model_config_path: gan_facies/configs/default/model.yaml
data_config_path: gan_facies/configs/default/data.yaml
training_config_path: gan_facies/configs/default/training.yaml
distributed_config_path: gan_facies/configs/default/distributed.yaml
experiment_tracking_config_path: gan_facies/configs/default/experiment_tracking.yaml
metrics_config_path: gan_facies/configs/default/metrics.yaml
