# Use for unit tests (DO NOT DELETE if you want to run the unit tests)
run_name: tmp_test
config_save_path: configs/runs/tmp_test/config
dataset_path: null  # use custom simple dataset instead
save_attn: True

model.data_size: 32

training.adv_loss: hinge
training.g_ema_decay: 0.999

training.batch_size: 2
training.log_step: 1
training.model_save_step: 2
training.sample_step: 2
training.total_step: 6

wandb.use_wandb: False
