# Use for unit tests (DO NOT DELETE if you want to run the unit tests)
run_name: tmp_test
config_save_path: configs/runs/tmp_test/config
dataset_path: null  # use custom simple dataset instead
save_attn: True

model.data_size: 32
model.attn_layer_num: [1, 2, 3]
model.d_conv_dim: 8
model.g_conv_dim: 8
model.full_values: True
model.init_method: orthogonal

training.adv_loss: hinge
training.g_ema_decay: 0.999
training.ema_start_step: 0

training.batch_size: 2
training.log_step: 1
training.model_save_step: 2
training.sample_step: 2
training.total_step: 6

wandb.use_wandb: False
