# Use for unit tests (DO NOT DELETE if you want to run the unit tests)
run_name: tmp_test
config_save_path: configs/runs/tmp_test/config
dataset_path: 'tests/datasets/data64.npy'  # use custom simple dataset
output_dir: res
save_attn: True
trunc_ampl: 1.0

model.attn_layer_num: [4]
model.data_size: 64
model.d_conv_dim: 12
model.g_conv_dim: 12
model.full_values: False
model.init_method: normal

training.adv_loss: wgan-gp
training.batch_size: 2
training.g_ema_decay: 1  # disable ema
training.d_ema_decay: 1  # disable ema
training.mixed_precision: True

training.log_step: 1
training.metric_step: 1000  # disable metric evaluation
training.model_save_step: 2
training.sample_step: 2
training.total_step: 2

clearml.use_clearml: False
wandb.use_wandb: False
