# Overwrite default configs
run_name: run1
config_save_path: res/configs/run1
output_dir: res
dataset_path: datasets/gansim_small.npy

data.num_workers: 2
model.data_size: 64
model.attn_layer_num: [2, 3]

training.total_step: 300
training.sample_step: 100
training.model_save_step: 100
training.metric_step: 100

clearml.use_clearml: False
wandb.use_wandb: False
