# Overwrite default configs
run_name: cond
config_save_path: res/configs/cond
output_dir: res
dataset_path: datasets/TI_analog_rongier_128_smaller.npy

data.num_workers: 2
model.data_size: 64
model.attn_layer_num: [2, 3]

training.total_step: 300
training.sample_step: 100
training.model_save_step: 100
training.metric_step: 100

clearml.use_clearml: False
wandb.use_wandb: False

# Conditional architecture
model.architecture: cond_sagan
model.cond_dim_ratio: 8
data.n_pixels_cond: 20
data.pixel_size_cond: 1
training.cond_penalty: 2.5
