# Overwrite default configs
run_name: run_wandb
config_save_path: res/configs/run_wandb
output_dir: res
dataset_path: datasets/gansim_small.npy

data.num_workers: 2
model.data_size: 64
model.attn_layer_num: [2, 3]

training.total_step: 300
training.sample_step: 100
training.model_save_step: 100
training.metric_step: 100

wandb.use_wandb: True
wandb.entity: null
wandb.project: test_sagan_with_wandb
wandb.mode: online

# No sweep
wandb.sweep_config_path: null
wandb.sweep: null
