--- !model
architecture: sagan
init_method: 'default'  # could be either 'default' or 'orthogonal'
data_size: 64  # could be either 32 or 64
full_values: True
z_dim: 128
g_conv_dim: 64
d_conv_dim: 64
