--- !training
# Note: training batch_size in in data sub-config

# interrupt_threshold: stop the training if the sum of the absolute losses are
# above this value (negative to disable)
interrupt_threshold: -1.0
save_boxes: True  # save the metric boxes
adv_loss: wgan-gp  # could be either 'wgan-gp' or 'hinge'
mixed_precision: False  # if True, use float16 instead of float32 for training

g_ema_decay: 1.0  # decay of generator's exponential moving average (1.0 = no decay)
d_ema_decay: 1.0
d_iters: 1  # d_iters: number of time to train discriminator each time generator is trained
g_lr: 0.0001
d_lr: 0.0004
# lambda_gp: gradient penalty factor in the loss
lambda_gp: 10.0
beta1: 0.0
beta2: 0.9
weight_decay: 0.0

# Step sizes
total_step: 100000
total_time: -1  # in sec, < 0 means no time limit
ema_start_step: 0  # only used if g_ema_decay < 1.0
log_step: 10
sample_step: 400  # save generated images every n steps
model_save_step: 1200  # save generator and discriminator every n steps
metric_step: 1200  # compute metrics every n steps
