--- !wandb
use_wandb: False
project: null  # (should be overwritten by the experiment config if use_wandb is True)
entity: null
group: null
mode: online
id: null  # used to resume a wandb run

sweep_config_path: null  # null to not sweep (note: 'program' argument is not required)
sweep: null
