# Overwrite default configs
run_name: run1
config_save_path: configs/runs/run1
dataset_path: datasets/gansim_small.npy
num_workers: 2

training.total_step: 300
training.sample_step: 100
training.model_save_step: 100
training.metric_step: 100
