# Overwrite default configs
run_name: cond
config_save_path: res/configs/cond
output_dir: res
dataset_path: datasets/gansim_small.npy

data.num_workers: 2
model.data_size: 64

training.total_step: 300
training.sample_step: 100
training.model_save_step: 100
training.metric_step: 100

clearml.use_clearml: False
wandb.use_wandb: False

model_config_path: configs/default/models/cond_sagan.yaml
model.cond_dim_ratio: 8
data.n_pixels_cond: 20
training.cond_penalty: 2.5
