# Overwrite default configs
run_name: run_clearml
config_save_path: res/configs/run_clearml
output_dir: res
dataset_path: datasets/gansim_small.npy
num_workers: 2

training.total_step: 300
training.sample_step: 100
training.model_save_step: 100
training.metric_step: 100

clearml.use_clearml: True
clearml.project_name: gan-facies-editing
clearml.task_name: test_sagan_with_clearml
clearml.tags: [usagan, gansim_small]
clearml.continue_last_task: null
