--- !model
architecture: cond_sagan  # should not be changed
init_method: 'default'  # could be either 'default' or 'orthogonal'
data_size: 64  # could be either 32, 64, 128 or 256
# attn_layer_num: number of the block(s) where attention is applied to the output (starting from 1)
# NOTE: the number of blocks depends on the data size only:
# data_size 32: 4 blocks, data_size 64: 5 blocks, data_size 128: 6 blocks, data_size 256: 7 blocks
attn_layer_num: [3, 4]
full_values: False
z_dim: 128
g_conv_dim: 64  # number of channels before the last layer of the generator
d_conv_dim: 64  # number of channels after the first layer of the discriminator

# cond_dim_ratio: define the number of channels of conditional feature maps
# cond_dim = base_dim // cond_dim_ratio
cond_dim_ratio: 8
